
typedef struct http_mime
{
  const char* ext;
  const char* type;
  int ext_len;
} HttpMime;
static const HttpMime HttpMimes[]=
{
  {"htm", "text/html", 3},
  {"html", "text/html", 4},
  {"js", "text/javascript", 2},
  {"mjs", "text/javascript", 3},
  {"jpg", "image/jpeg", 3},
  {"jpeg", "image/jpeg", 4},
  {"png", "image/png", 3},
  {"webp", "image/webp", 4},
  {"svg", "image/svg+xml", 3},
  {"css", "text/css", 3},
  {"mp3", "audio/mpeg", 3},
  {"mp4", "video/mp4", 3},
  {"json", "application/json", 4},
  {"ico", "image/vnd.microsoft.icon", 3},
  {"pdf", "application/pdf", 3},
  {"zip", "application/zip", 3},
  {"rar", "application/vnd.rar", 3},
  {"doc", "application/msword", 3},
  {"docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 4},
  {"xls", "application/vnd.ms-excel", 3},
  {"xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", 4},
  {"ppt", "application/vnd.ms-powerpoint", 3},
  {"pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation", 4},
  {"txt", "text/plain", 3},
  {"xml", "application/xml", 3},
  {"bmp", "image/bmp", 3},
  {"wav", "audio/wav", 3},
  {"bin", "application/octet-stream", 3},
  {"avi", "video/x-msvideo", 3},
  {"csv", "text/csv", 3},

  {"aac", "audio/aac", 3},
  {"abw", "application/x-abiword", 3},
  {"apng", "image/apng", 4},
  {"arc", "application/x-freearc", 3},
  {"avif", "image/avif", 4},
  {"azw", "application/vnd.amazon.ebook", 3},
  {"bz", "application/x-bzip", 2},
  {"bz2", "application/x-bzip", 3},
  {"cda", "application/x-cdf", 3},
  {"csh", "application/x-csh", 3},
  {"eot", "application/vnd.ms-fontobject", 3},
  {"epub", "application/epub+zip", 4},
  {"gz", "application/gzip", 2},
  {"ics", "text/calendar", 3},
  {"jar", "application/java-archive", 3},
  {"jsonld", "application/ld+json", 6},
  {"midi", "audio/midi", 4},
  {"mid", "audio/x-midi", 3},
  {"mpeg", "video/mpeg", 4},
  {"mpkg", "application/vnd.apple.installer+xml", 4},
  {"odp", "application/vnd.oasis.opendocument.presentation", 3},
  {"ods", "application/vnd.oasis.opendocument.spreadsheet", 3},
  {"odt", "application/vnd.oasis.opendocument.text", 3},
  {"oga", "audio/ogg", 3},
  {"ogv", "video/ogg", 3},
  {"ogx", "application/ogg", 3},
  {"opus", "audio/ogg", 4},
  {"otf", "font/otf", 3},
  {"php", "application/x-httpd-php", 3},
  {"rtf", "application/rtf", 3},
  {"sh", "application/x-sh", 2},
  {"tar", "application/x-tar", 3},
  {"tif", "image/tiff", 3},
  {"tiff", "image/tiff", 4},
  {"ts", "video/mp2t", 2},
  {"ttf", "font/ttf", 3},
  {"vsd", "application/vnd.visio", 3},
  {"weba", "audio/webm", 4},
  {"webm", "video/webm", 4},
  {"woff", "font/woff", 4},
  {"woff2", "font/woff2", 5},
  {"xhtml", "application/xhtml+xml", 5},
  {"xul", "application/vnd.mozilla.xul+xml", 3},
  {"3gp", "video/3gpp", 3},
  {"3g2", "video/3gpp2", 3},
  {"7z", "application/x-7z-compressed", 2}
};
static const int HttpMimesLen=sizeof(HttpMimes)/sizeof(HttpMime);
