let companies=[  
  {     
    company:"晟建环境科技有限公司",
    location:'金银湖科技园15栋2单元202',
    summary:'',
    services: ['销售污水处理设备和相关配件','承接污水处理工程'],
    imgs:['晟建.webp', '晟建会议室.webp', '晟建办公室.webp'],
    contacts:['微信群@晟建'],
  },
  { 
    company:"艺术速递定制画框艺术品有限公司",
    location:'金银湖科技园2栋602',
    services: ['高品质艺术画框定制','字画装裱卷轴','大幅图像激光打印','字画艺术品打包邮寄'],
    imgs:['艺术快递.webp','艺术快递2_1.webp','艺术快递2_2.webp','艺术快递2_3.webp','艺术快递3_1.webp','艺术快递3_2.webp','艺术快递3_3.webp','艺术快递3_4.webp','艺术快递3_5.webp','艺术快递1_1.webp','艺术快递1_2.webp','艺术快递1_4.webp','艺术快递1_5.webp','艺术快递1_6.webp','艺术快递1_7.webp','艺术快递1_8.webp', '艺术速递内景.jpg', '艺术速递logo.jpg'],  
    imgs2:['艺术速递大门.jpg', ],
    contacts:['微信群@周林平'],  
  },
  { 
    company:"玲明软件开发技术服务（个人）",
    location:'金银湖科技园16栋',
    summary:'',
    services: ['电脑系统、应用软件安装维护','Excel/Word等文件资料自动化处理','管理软件、工作流程自动化软件开发','其它任意软件开发需求'],
    services2: ['文件存储管理系统（历史记录、多人协作）','网站开发','微信小程序、手机APP开发'],
    imgs:['qiuzen20240703.webp'],  
    contacts:['微信：TobeBuda'],  
  },
  { 
    company:"品牌女装",
    location:'金银湖科技园7栋4单元3楼',
    summary:'',
    env:['品牌女装.jpg'],  
    closed: true,
  },
  { 
    company:"普诺克精密工具",
    location:'金银湖科技园9栋1楼',
    summary:'招聘能上12小时夜班的年轻人',
    env:['普诺克前台.jpg'],
    contacts:['微信群@大宝'],
    closed: true,
  },
  { 
    company:"武汉科印",
    location:'金银湖科技园12栋',
    env:['武汉科印办公室.jpg', '武汉科印大门.jpg', '武汉科印大厅.jpg', '武汉科印礼品架.jpg', '飞控自动化展厅.jpg', '飞控自动化走廊.jpg'],    
    closed: true,
  },
  { 
    company:"科电中威电气",
    location:'金银湖科技园12栋',
    env:['科电中威电气大门.jpg'],    
    closed: true,
  },
  { 
    company:"凯迪正大电气",
    location:'金银湖科技园12栋',
    env:['凯迪正大电气电梯.jpg', '凯迪正大电气前台.jpg', '凯迪正大电气植物.jpg', '飞控自动化会议室.jpg', '飞控自动化展厅.jpg', '飞控自动化走廊.jpg'],    
    closed: true,
  },
  { 
    company:"定制盒饭团餐",
    location:'',
    env:['定制盒饭团餐.jpg'],    
    closed: true,
  },
  { 
    company:"飞控自动化工程",
    location:'金银湖科技园12栋',
    env:['飞控自动化大厅.jpg', '飞控自动化电梯.jpg', '飞控自动化花架.jpg', '飞控自动化会议室.jpg', '飞控自动化展厅.jpg', '飞控自动化走廊.jpg'],    
    closed: true,
  },
  { 
    company:"达译自动化工程",
    location:'金银湖科技园12栋',
    env:['达译自动化.jpg'],    
    closed: true,
  },
  { 
    company:"武汉天怡食品",
    location:'金银湖科技园12栋',
    summary:'招聘糕点制作和礼盒包装小时工，16元/小时',
    detail:['天怡食品找小时工.jpg'],
    env:['天怡食品招牌.jpg', '天怡食品广告1.jpg','天怡食品绿豆糕.jpg','天怡食品喜饼.jpg',],
    closed: true,
  },
  { 
    company:"优点生物",
    location:'金银湖科技园12栋',
    summary:'招聘车间普工，4k-7k，五险一金，包食宿',
    detail:['优点生物普工.jpg'],
    env:['优点生物大门.jpg'],
    closed: true,
  },
  { 
    company:"武商奥莱",
    location:'金银湖科技园12栋',
    summary:'',
    detail:[],
    env:['武商奥莱.jpg'], 
    closed: true,
  },
  { 
    company:"巷子戏法",
    location:'金银湖科技园17栋6楼',
    summary:'',
    env:['巷子戏法大门.jpg', '巷子戏法电梯.jpg', '巷子戏法盆栽.jpg', '巷子戏法logo.jpg'],    
    closed: true,
  },
  { 
    company:"冰块厂",
    location:'金银湖科技园',
    summary:'招聘能开车送货、搬东西的年轻男子',
    env:[],
    contacts:['本群@大宝小贝'],
    closed: true,
  },
  { 
    company:"开拓智能装备",
    location:'金银湖科技园',
    summary:'招聘有销售经验的销售人员',
    env:['开拓智能前台.jpg', '开拓智能文化.jpg'],
    contacts:['吳小姐 180-6215-9577', '服务热线 18062668722'],
    closed: true,
  },
  { 
    company:"樱花糕坊",
    location:'金银湖科技园',
    summary:'招聘甜点制作工，3800元-6000元',
    detail:['樱花糕坊甜点工.jpg'],
    closed: true,
  },
  { 
    company:"吉米快修",
    location:'金银湖南三街18-1号',
    env:['吉米快修.jpg'],    
    closed: true,
  },
];

export default companies;