let goods=[
  { 
    name:"美都麒麟西瓜",
    des:"每个8斤左右",
    provider: "刘 15238808979",
    location:'金银湖科技园',
    price: 2,
    price_in: 1.7,
    price_unit:'元/斤',
    pics:['西瓜刘.jpg'],  
    closed: false,
  },
  { 
    name:"牛奶小糖丸西瓜",
    des:"西瓜很小，每个3斤左右",
    provider: "李继鹏",
    location:'金银湖科技园',
    price: 3,
    price_in: 2.5,
    price_unit:'元/斤',
    pics:['小西瓜李继鹏.jpg'],  
    closed: false,
  },
  { 
    name:"李子",
    provider: "吴",
    location:'金银湖科技园',
    price: 6,
    price_in: 5,
    price_unit:'元/斤',
    pics:['李子吴.jpg'],  
    closed: false,
  },
  { 
    name:"榴莲",
    provider: "吴",
    location:'金银湖科技园',
    price: 19.8,
    price_in: 16,
    price_unit:'元/斤',
    pics:['榴莲吴.jpg'],  
    closed: false,
  },
  { 
    name:"耙耙柑",
    provider: "吴",
    location:'金银湖科技园',
    price: 3.4,
    price_in: 2.7,
    price_unit:'元/斤',
    pics:['耙耙柑吴.jpg'],  
    closed: false,
  },
  { 
    name:"桃子",
    provider: "吴",
    location:'金银湖科技园',
    price: 4,
    price_in: 3.2,
    price_unit:'元/斤',
    pics:['桃子吴.jpg'],  
    closed: false,
  },
  { 
    name:"蓝莓",
    provider: "吴",
    location:'金银湖科技园',
    price: 7.5,
    price_in: 6,
    price_unit:'元/盒',
    pics:['蓝莓吴.jpg'],  
    closed: false,
  },
  { 
    name:"樱桃",
    provider: "吴",
    location:'金银湖科技园',
    price: 15,
    price_in: 12,
    price_unit:'元/斤',
    pics:['樱桃吴.jpg'],  
    closed: false,
  },
  { 
    name:"栀子花",
    provider: "吴",
    location:'金银湖科技园',
    price: 0.5,
    price_in: 0.4,
    price_unit:'元/朵',
    pics:['栀子花小女人.jpg'],  
    closed: false,
  },
];

export default goods;